### PR TITLE
[0.10.0] Indicators for Enrollment via Randomization

### LINKED ISSUE #247: Account page title has no localization, instead returns "profile.title - MySK"
### Before we begin

- [X] I have already searched the Issues page, and I am sure this bug report isn’t a duplicate.

### What happened?

Screenshot 2567-04-22 at 11 11 48
The title bar for "Accounts" page is set to "profile.title".

### Steps to reproduce

1. Use a teacher or student account.
2. Navigate to the "Accounts" page.
3. See the page titled as "profile.title"

### Version

0.10.0 (Preview)

### What browsers are you seeing the problem on?

Chrome

### LINKED ISSUE #266: Adding a contact returns an error
### Before we begin

- [X] I have already searched the Issues page, and I am sure this bug report isn’t a duplicate.

### What happened?

www mysk school_en-US_account_contacts(iPad Pro)
Trying to add a contact would result in a "Task failed, please try again" toast pop-up.

### Steps to reproduce

1. Log in to MySK with either a student or a teacher account.
2. Navigate to the 'About You' page.
3. Add a contact, and fill in sample details.
4. It will return a 'Try again later' error.

### Version

0.9.5

### What browsers are you seeing the problem on?

Chrome, Safari

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
## Features
- Indicators for enrollment via randomization
  Resolves FRO-97 [(link)](https://linear.app/skiso/issue/FRO-97/indicators-for-enrollment-via-randomization)
  - Asterisk in Student List Printout
    Resolves FRO-98
  - Asterisk in Elective Student List Card
    Resolves FRO-103
- Fade out behind Search in Elective Student List Card    
- Name in Person Card now has a shorter line height

## Code Changes
- Added missing keys to `ElectiveSubject` type
- Person Card now supports suffix

## Fixes
- Classroom Contacts Menu is not translated
  Fixes FRO-124
- Adding Contacts to Person returns an error
  Fixes #266
  Fixes FRO-121
- Account page title has no localization, instead returns “profile.title - MySK”
  Fixes #247
  Fixes FRO-107
- Teach Electives is missing `classes` translation file

## Preview
This is the current main feature PR. Preview available at https://pr.mysk.school/.

### CODE REVIEW

File: components/classes/StudentListTableBody.tsx [hunk 1]
```diff
@@ -78,6 +78,17 @@ const StudentListTableBody: StylableFC<{
             </td>
           )}
 
+          {/* Enrollment via randomization */}
+          {options.columns.includes("randomized") && (
+            <td className="!border-l-0">
+              {student.chosen_elective?.randomized_students.some(
+                (randomizedStudent) => student.id === randomizedStudent.id,
+              )
+                ? "*"
```
Comment (pixelpxed) [inline components/classes/StudentListTableBody.tsx:87]: Putting just a "*" as a mark that the student is randomly enrolled is good and subtle, but not too subtle for the user!

The if statement here for " " or "*" is put to good use and simple too!

File: pages/news/[id].tsx
Comment (pixelpxed) [inline pages/news/[id].tsx:1]: Is this an effort to simplify this News feature? Just asking.

**Review by pixelpxed — APPROVED** [review]
LGTM, one unrelated question though.

File: pages/news/[id].tsx
Comment (SiravitPhokeed) [reply pages/news/[id].tsx:1]: We recently migrated to Plausible, and during the migration I changed the page view tracking from using the exact URL (like `/en-US/classes/604/print`) to the pathname (`/classes/[classNumber]/print`).

Enrollment List Printout is at `/teach/electives/[id]/print`, so it would make sense to move News Article to `/news/[id]`.
