### PR TITLE
Fix: Teacher related issues

### LINKED ISSUE #114: Data Check fails to set up teacher if not advisor
**Describe the bug**
The `setupPerson` function used by Data Check in Welcome blindly uses the Class Advisor At field without checking if the field is empty, causing the process to fail if the user is not an Advisor. The user thus cannot progress to the next Section.

**To Reproduce**

1. Log in to an account that has not been onboarded
2. Click on “Continue”
3. Fill in the required fields except Class Advisor At
4. Click on “Save and continue”
5. See that the Button does nothing.

**Expected behavior**
The function should ignore the field if empty.

### LINKED ISSUE #117: Default Navigation always shown on first load even when logged in
**Describe the bug**
Navigation currently only refreshes on route change. On first load, Navigation just remains in its default state/

**To Reproduce**

1. Log in
2. Reload to reset Navigation
3. See wrong Navigation

**Expected behavior**
After user data is fetched, Navigation should be tailored towards the user, like students, teachers, class advisors, etc.

**Screenshots**
image

**Additional context**
This is probably because Navigation doesn't update after `useUser` finishes fetching.

### LINKED ISSUE #118: Add Contacts fail with RLS enabled
**Describe the bug**
If RLS is enabled for the `contact` table in the Supabase console, the Add Contacts Dialog fails.

**To Reproduce**

1. Go to Manage Class
2. Click on “Add contacts”
3. Fill in required information
4. Click “Add”
5. See error in console output

**Expected behavior**
“Add” should create the Contact.

### LINKED ISSUE #119: Class Advisors cannot remove class Contacts
**Describe the bug**
Class Advisors can add class Contacts, but cannot edit or remove them once they’re added. They’re there forever now. No return.

**To Reproduce**

1. Go to Manage Class
2. Add a Contact
3. See no way to edit or remove it

**Expected behavior**
A delete Button on each Contact to delete the Contact.

### PR DESCRIPTION
**Pull request by Jimmy-Tempest**
**Fixes**
- Teacher advisory being mandatory
  Fixes #114 
- Navbar reset to default
  Fixes #117 
- Add contact fail and not delectable
  Fixes #118 
  Fixes #119

### CODE REVIEW

File: src/pages/class/[classNumber]/manage.tsx [hunk 1]
```diff
@@ -354,6 +359,16 @@ const ContactSection = ({
...
             className="!w-initial"
+            allowEdit={allowEdit}
+            onDelete={() => {
+              removeContactFromClassroom(
+                supabase,
+                contact.id,
+                classroomId
+              ).then(() => {
+                router.replace(router.asPath);
+              });
```
Comment (SiravitPhokeed) [inline src/pages/class/[classNumber]/manage.tsx:370]: Why not `await`?

File: src/components/ContactChip.tsx [hunk 2]
```diff
@@ -14,59 +19,67 @@ import { getContactURL } from "@utils/helpers/contact";
...
+                className="text-stroke text-stroke-0.25 text-stroke-surface-1 -ml-2 text-secondary"
+              />
+            )}
+            {contact.includes!.parents && (
+              <MaterialIcon
+                icon="escalator_warning"
+                className="text-stroke text-stroke-0.25 text-stroke-surface-1 -ml-2 text-primary"
+              />
+            )}
+            {contact.includes!.students && (
```
Comment (SiravitPhokeed) [inline src/components/ContactChip.tsx:70]: Why not just make this property required in the type? I believe this is literally the only place that uses this.

File: src/pages/class/[classNumber]/manage.tsx [hunk 3]
```diff
@@ -525,8 +541,10 @@ const Class: NextPage<{
...
         onSubmit={async (contact) => {
-          const { data: createdContact, error: contactCreationError } =
-            await createContact(contact);
+          const {
+            data: createdContact,
+            error: contactCreationError,
+          } = await createContact(supabase, contact);
 
           if (contactCreationError) {
             console.error(contactCreationError);
```
Comment (SiravitPhokeed) [inline src/pages/class/[classNumber]/manage.tsx:550]: Not sure when this was written but isn’t the error logged from inside the function anyway? If not then it should be.

File: src/utils/backend/database.ts [hunk 4]
```diff
@@ -32,6 +32,11 @@ export function db2Contact(
     },
     value: contact.value,
     type: contact.type,
+    includes: {
+      students: contact.include_students!,
+      parents: contact.include_parents!,
+      teachers: contact.include_teachers!,
```
Comment (SiravitPhokeed) [inline src/utils/backend/database.ts:38]: Don’t overuse `!`. It’s like a middle finger to the compiler. Like an “I’m 100% sure this is not null why are you saying it is” to the compiler. I don’t know why you’re using it here so I can’t really comment on the validity of this so do check why and get back to me.

**Review by SiravitPhokeed — APPROVED** [review]
_LGTM!_
