### PR TITLE
[0.10.0] MySK API Setup

### LINKED ISSUE #224: Allergies field returns an empty chip box for each character typed.
### Before we begin

- [x] I have already searched the Issues page, and I am sure this bug report isn’t a duplicate.

### What happened?

Screenshot 2567-02-08 at 09 43 10
The allergies input field will insert a blank chip box for each character typed, and pressing enter will select the chip.

### Steps to reproduce

1. Use a teacher or student account.
2. Navigate to the 'Account' tab, then type any character such as "ทางคนอย่างเธอ" in the allergies field
3. See the blank chip box that appears for each character.

### Version

0.8.12

### What browsers are you seeing the problem on?

Chrome, Safari

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
**Features**
- `mysk.fetch` for server-side (with API key) and client-side (via proxy protected by CORS)
  Resolves FRO-67

**Fixes**
- The background color of Lookup Details Card does not match that in Figma
- Allergies Chip Field issue resolved by upgrading SKCom
  Fixes #224
  Related to FRO-61

**Notes**
Preview available at https://pr.mysk.school/.

### CODE REVIEW

File: utils/backend/mysk/fetchMySKProxy.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+>(
+  path: string,
+  options?: Partial<RequestInit & { query: Query }>,
+): Promise<FetchReturn<Data>> {
+  // Fetch the data via the MySK API proxy
+  const response = await fetch("/api/mysk-api-proxy", {
+    method: "POST",
+    headers: { "Content-Type": "application/json" },
+    body: JSON.stringify({ path, options }),
+  });
```
Comment (SiravitPhokeed) [inline utils/backend/mysk/fetchMySKProxy.ts:24]: I want your opinion on this. Is it bad that all fetches are _technically_ POST? Does it matter?

Comment (SiravitPhokeed) [reply utils/backend/mysk/fetchMySKProxy.ts:24]: Okie!
